name: Docker Image CI

on:
  push:
    branches:
      - main
      - 'feat/012-hebergement-du-back'
      - development

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        registry: registry-kin.hyver.ingeeniex.com
        # Username used to log against the Docker registry
        username: ${{ secrets.username }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.password }}
      # Specifies whether the given registry is ECR (auto, true or false)
    - name: Set outputs
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: Check outputs
      run: echo ${{ steps.vars.outputs.sha_short }}
    - name: Build the Docker image
      run: cd o-notes; docker build . --file ./docker/8.2/Dockerfile --tag registry-kin.hyver.ingeeniex.com/onotes-back:${{ steps.vars.outputs.sha_short }}
    - name: Push to registry   
      run: docker push registry-kin.hyver.ingeeniex.com/onotes-back:${{ steps.vars.outputs.sha_short }}
    - name: Deploy to CapRover
      uses: caprover/deploy-from-github@v1.1.2
      with: 
        server: ${{ secrets.CAPROVER_SERVER }}
        app: ${{ secrets.CAPROVER_APP }}
        token: ${{ secrets.CAPROVER_TOKEN }}
        image: registry-kin.hyver.ingeeniex.com/onotes-back:${{ steps.vars.outputs.sha_short }}